### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by wingscot** [hongliuliao/simple-flow#1]
c/agent/file_agent.cpp -o src/agent/file_agent.o
src/agent/file_agent.cpp:18:24: 错误：simple_log.h：没有那个文件或目录
src/agent/file_agent.cpp: In member function ‘void FileAgent::start_watch(std::string, bool)’:
src/agent/file_agent.cpp:56: 错误：‘LOG_ERROR’在此作用域中尚未声明
make: *** [src/agent/file_agent.o] 错误 1

**Comment by hongliuliao** [comment]
fix compile err
